#!/bin/bash

SCRIPT_PATH="${BASH_SOURCE[0]}"
SCRIPT_DIR=`dirname "${SCRIPT_PATH}"`
cd "$SCRIPT_DIR"

inst_name='fractalvalley.net-F1'

# Find an instance named "fractalvalley.net-F1".
inst_id=$(aws ec2 describe-instances --output text --filter 'Name=tag:Name,Values=$inst_name' | grep ^INSTANCES | sed -E 's/^.*\s(i-[0-9a-z]+).*$/\1/')

if [[ $inst_id =~ i-[0-9a-z]+ ]]
then
  ../../../framework/aws/ec2_instance_feeder connect ../feeders/$inst_id 120 root &
else
  echo "$0: Error: Found instance id: '$inst_id', which doesn't look right."
  exit 1
fi
