#!/bin/bash

# This script starts the host application build for sw or hw.

# Usage:
#   launch hw
#   launch sw

if [[ "$1" = "" ]];
then
    echo "Usage: launch [sw/hw]"
    exit 1
fi


../host_app/$1/host &
HOST_PID=$!
python server.py &
SERVER_PID=$!

function finish {
    # Kill child processes
    kill $HOST_PID
    kill $SERVER_PID
    echo "Killed host app and web server"
}

trap finish EXIT

wait

